### ISSUE TITLE
Need more information. Thanks!

### ISSUE THREAD

**Issue by Senqi-Guan** [FedDefender/FedDefender#1]
Could you please share your requirements.txt? And share more details about how to prepare data、how to  train and test? Thank you very much.

**Comment by deu30303** [comment]
Hello, thank you for your interest in our work!

- I have listed the major required packages in the README.
- You can download the data by setting 'download=True' in the Torch dataset.

Once again, thank you for your interest.

**Comment by Senqi-Guan** [comment]
Thank you for your reply！
