### ISSUE TITLE
about the FEMINST generation command

### ISSUE THREAD

**Issue by MillionaireChen** [FedDefender/FedDefender#2]
Hi, I am reproducing your paper. Thanks for your contributions. But I want to keep everything the same as yours. 
![image](https://github.com/deu30303/FedDefender/assets/35960345/dce51404-2753-4427-b7d2-209db2a1d5e1)

**Comment by deu30303** [comment]
Thank you for your interest in our work!
  
I'll share the dataset with you once the email is sent.

Once again, thank you for your interest.
