### ISSUE TITLE
Takes up a lot of computer memory and prevents it from running smoothly.

### ISSUE THREAD

**Issue by Senqi-Guan** [FedDefender/FedDefender#3]
Hi, I am reproducing your paper. Thanks for your contributions. 
    But I'm having some issues where when using the tiny-imagenet dataset, my computer gets stuck with too much memory usage. 
    What kind of hardware do you use to run this data set? 
    How much computer memory is enough, 32G, or 64G, or more?

**Comment by deu30303** [comment]
Thank you for your interest in our work! 

The study was conducted using A100 80GB and V100 32GB. 
If you are using a smaller GPU, please conduct the experiment by reducing the image size or batch size.

**Comment by Senqi-Guan** [comment]
OK，Thank you！！！
